// Code generated by 'go generate'; DO NOT EDIT.

package winipcfg

import (
	"syscall"
	"unsafe"

	"golang.org/x/sys/windows"
)

var _ unsafe.Pointer

// Do the interface allocations only once for common
// Errno values.
const (
	errnoERROR_IO_PENDING = 997
)

var (
	errERROR_IO_PENDING error = syscall.Errno(errnoERROR_IO_PENDING)
)

// errnoErr returns common boxed Errno values, to prevent
// allocations at runtime.
func errnoErr(e syscall.Errno) error {
	switch e {
	case 0:
		return nil
	case errnoERROR_IO_PENDING:
		return errERROR_IO_PENDING
	}
	// TODO: add more here, after collecting data on the common
	// error values see on Windows. (perhaps when running
	// all.bat?)
	return e
}

var (
	modiphlpapi = windows.NewLazySystemDLL("iphlpapi.dll")

	procCancelMibChangeNotify2  = modiphlpapi.NewProc("CancelMibChangeNotify2")
	procGetAdaptersAddresses    = modiphlpapi.NewProc("GetAdaptersAddresses")
	procGetIpForwardTable2      = modiphlpapi.NewProc("GetIpForwardTable2")
	procFreeMibTable            = modiphlpapi.NewProc("FreeMibTable")
	procCreateIpForwardEntry2   = modiphlpapi.NewProc("CreateIpForwardEntry2")
	procSetIpForwardEntry2      = modiphlpapi.NewProc("SetIpForwardEntry2")
	procDeleteIpForwardEntry2   = modiphlpapi.NewProc("DeleteIpForwardEntry2")
	procNotifyIpInterfaceChange = modiphlpapi.NewProc("NotifyIpInterfaceChange")
)

func cancelMibChangeNotify2(NotificationHandle uintptr) (result int32) {
	r0, _, _ := syscall.Syscall(procCancelMibChangeNotify2.Addr(), 1, uintptr(NotificationHandle), 0, 0)
	result = int32(r0)
	return
}

func getAdaptersAddresses(Family uint32, Flags uint32, Reserved uintptr, AdapterAddresses *wtIpAdapterAddresses, SizePointer *uint32) (result uint32) {
	r0, _, _ := syscall.Syscall6(procGetAdaptersAddresses.Addr(), 5, uintptr(Family), uintptr(Flags), uintptr(Reserved), uintptr(unsafe.Pointer(AdapterAddresses)), uintptr(unsafe.Pointer(SizePointer)), 0)
	result = uint32(r0)
	return
}

func getIpForwardTable2(family AddressFamily, table *wtMibIpforwardTable2) (result int32) {
	r0, _, _ := syscall.Syscall(procGetIpForwardTable2.Addr(), 2, uintptr(family), uintptr(unsafe.Pointer(table)), 0)
	result = int32(r0)
	return
}

func freeMibTable(memory uintptr) {
	syscall.Syscall(procFreeMibTable.Addr(), 1, uintptr(memory), 0, 0)
	return
}

func createIpForwardEntry2(route *wtMibIpforwardRow2) (result int32) {
	r0, _, _ := syscall.Syscall(procCreateIpForwardEntry2.Addr(), 1, uintptr(unsafe.Pointer(route)), 0, 0)
	result = int32(r0)
	return
}

func setIpForwardEntry2(route *wtMibIpforwardRow2) (result int32) {
	r0, _, _ := syscall.Syscall(procSetIpForwardEntry2.Addr(), 1, uintptr(unsafe.Pointer(route)), 0, 0)
	result = int32(r0)
	return
}

func deleteIpForwardEntry2(route *wtMibIpforwardRow2) (result int32) {
	r0, _, _ := syscall.Syscall(procDeleteIpForwardEntry2.Addr(), 1, uintptr(unsafe.Pointer(route)), 0, 0)
	result = int32(r0)
	return
}

func notifyIpInterfaceChange(route *wtMibIpforwardRow2) (result int32) {
	r0, _, _ := syscall.Syscall(procNotifyIpInterfaceChange.Addr(), 1, uintptr(unsafe.Pointer(route)), 0, 0)
	result = int32(r0)
	return
}
